---
- name: Установка gzip
  apt:
    name: gzip
    state: present
  become: yes

- name: Установка Docker
  apt:
    name: docker.io
    state: present
  become: yes

- name: Установка Docker Compose
  apt:
    name: docker-compose
    state: present
  become: yes
